[package]
name = "deeplearning"
version = "0.1.0"
authors = ["Rene Eichhorn <rene.eichhorn@mni.thm.de>"]

[dependencies]
log = "0.3.5"
rand = "0.3.13"
scoped_threadpool = "0.1.6"
byteorder = "0.4.2"
rustc-serialize = "0.3.16"
bincode = { git = "https://github.com/Auruss/bincode.git" }
