[package]
name = "deeplearning"
version = "0.1.0"
authors = ["Rene Eichhorn <rene.eichhorn@mni.thm.de>"]

[dependencies]
log = "0.3.5"
rand = "0.3.13"
scoped_threadpool = "0.1.6"
byteorder = "0.4.2"
serde = "0.7.*"
serde_macros = "0.7.*"
bincode = "0.5.0"
